name: build backend image

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yaml'
    branches:
      - main

jobs:
  push:
    name: "backend:build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/wiwichips/hell0-ka8te-backend:${{ github.sha }}
  test:
    name: "backend:test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull and test image
        run: |
          docker pull ghcr.io/wiwichips/hell0-ka8te-frontend:${{ github.sha }}
          docker run -d -p 8000:8000 ghcr.io/wiwichips/hell0-ka8te-frontend:${{ github.sha }}
          sleep 10
          curl localhost:8000/api/status
          exit $?
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/wiwichips/hell0-ka8te-frontend:${{ steps.date.outputs.date }}
      - uses: actions/delete-package-versions@v4
                                                                                                       


